Residence integration + configurable "No ... near shop" messages
myzticbean/QSFindItemAddOn pull request #45
Opened 2024-07-17 17:50 UTC by SengyEU

2024-07-17 18:20 UTC, myzticbean commented
@SengyEU I am good with the rest of the changes. Please address the above mentioned comments, and its good to merge.

2024-07-17 19:15 UTC, SengyEU commented
Wdym? I dont see any comments anywhere...

2024-07-17 19:17 UTC, myzticbean commented
> Wdym? I dont see any comments anywhere...

@SengyEU I tagged ur name now in the review comments, see if you are able to view now.

2024-07-17 19:35 UTC, SengyEU commented
Nope, i dont think the comments show up until you submit the review

2024-07-17 19:35 UTC, myzticbean requested changes

2024-07-17 19:36 UTC, myzticbean commented
> Nope, i dont think the comments show up until you submit the review

sorry my bad, just did

2024-07-17 19:38 UTC, SengyEU commented on pom.xml
> +            <systemPath>${project.basedir}/lib/Residence5.1.5.1.jar</systemPath>
oh yea, the gitignore must have taken it out

2024-07-17 19:38 UTC, SengyEU commented on README.md
> +- Residence support for fetching the residence the shop is in (including subzones)
👍

2024-07-17 19:46 UTC, SengyEU commented
Here you go

2024-07-18 15:15 UTC, myzticbean approved these changes

2024-07-18 15:16 UTC, merged